# Generated by Django 4.0.3 on 2022-03-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('vehicle_no', models.CharField(max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('vehicleDate', models.DateField()),
                ('fuelType', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Petrol-CNG', 'Petrol-CNG')], max_length=15)),
                ('ownerChange', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth')], max_length=15)),
                ('OwnerName', models.CharField(max_length=100)),
                ('aadharNo', models.IntegerField()),
                ('ownerAddress', models.TextField()),
                ('sellerName', models.CharField(max_length=100)),
                ('sellerAddress', models.TextField()),
                ('mobileNo', models.IntegerField()),
                ('purchaseDate', models.DateField()),
                ('purchaseAmt', models.FloatField(max_length=7)),
                ('advanceGiven', models.FloatField(max_length=7)),
                ('balanceRemaining', models.FloatField(blank=True, max_length=7)),
                ('agentExcuse', models.FloatField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('carmodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cardetails.car')),
                ('travelling', models.FloatField(max_length=7)),
                ('meterWork', models.FloatField(max_length=7)),
                ('repairingWork', models.FloatField(max_length=7)),
                ('dentingAndPainting', models.FloatField(max_length=7)),
                ('accessoryWork', models.FloatField(max_length=7)),
                ('rubbingPolish', models.FloatField(max_length=7)),
                ('total', models.FloatField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('carmodel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cardetails.car')),
                ('buyerName', models.CharField(max_length=100)),
                ('buyerAddress', models.TextField()),
                ('mobile', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('dealDate', models.DateField()),
                ('dealAmt', models.FloatField(max_length=7)),
                ('advanceAmt', models.FloatField(max_length=7)),
                ('balanceAmt', models.FloatField(blank=True, max_length=7)),
                ('documentCharges', models.FloatField(max_length=7)),
            ],
        ),
    ]
